version: '2'  

services:  
    node: 
        image: .
        ports: 
            - 3000:3000
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017        
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - ./mongo-db.sh:/docker-entrypoint-initdb.d/mongo-db.sh:ro
    redis: 
        image: redis:latest
        ports: 
            - 6379:6379